// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClwebVxMWNm9nrjv-DXnJCrbhxf9-Ja68',
    appId: '1:335394461556:web:2da13f163ab51b1c343e21',
    messagingSenderId: '335394461556',
    projectId: 'uaspemob-af22f',
    authDomain: 'uaspemob-af22f.firebaseapp.com',
    storageBucket: 'uaspemob-af22f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxk_sWo0oawwBsaBMu9bk9k7usp_23bVo',
    appId: '1:335394461556:android:e0400653464916da343e21',
    messagingSenderId: '335394461556',
    projectId: 'uaspemob-af22f',
    storageBucket: 'uaspemob-af22f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvsmtYHdTIRTjvGpQgnuyBPJ3Ia2-5fMM',
    appId: '1:335394461556:ios:52e65b801966a1bb343e21',
    messagingSenderId: '335394461556',
    projectId: 'uaspemob-af22f',
    storageBucket: 'uaspemob-af22f.firebasestorage.app',
    iosBundleId: 'com.example.uaspemob',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvsmtYHdTIRTjvGpQgnuyBPJ3Ia2-5fMM',
    appId: '1:335394461556:ios:52e65b801966a1bb343e21',
    messagingSenderId: '335394461556',
    projectId: 'uaspemob-af22f',
    storageBucket: 'uaspemob-af22f.firebasestorage.app',
    iosBundleId: 'com.example.uaspemob',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClwebVxMWNm9nrjv-DXnJCrbhxf9-Ja68',
    appId: '1:335394461556:web:96bf3f47699ef513343e21',
    messagingSenderId: '335394461556',
    projectId: 'uaspemob-af22f',
    authDomain: 'uaspemob-af22f.firebaseapp.com',
    storageBucket: 'uaspemob-af22f.firebasestorage.app',
  );
}
